# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d064b336fb2b5ae7566e721abc42ea16e1be1b12a552d6e65caed44fe49eea45c8bb294d2c6e1a9102002e70b49e8292750242d81b9abbc13bf929f86c57df5e

test:
  secret_key_base: 2dfdab9ffb3e7ea09ae15351f4a0225a3b91b3058f4dd1ef7a59dcdf7ccd4f324b48ac54039e10cb2746b45ca94d030e06225de5a947d6155546f462e492d375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
